<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Program.cs" />
    <Compile Include="Doubles.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)../../mod/Spire1Code/Config/Spire1Config.cs" Link="Spire1Config.cs" />
    <Compile Include="$(MSBuildThisFileDirectory)../../mod/Spire1Code/Run/Spire1RunContent.cs" Link="Spire1RunContent.cs" />
  </ItemGroup>
</Project>
